#!/usr/bin/env bun

import { existsSync, mkdirSync, rmSync, copyFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const image = process.env.ZEVM_HIVE_IMAGE ?? "zevm/hive-client:local";
const zigVersion = process.env.ZIG_VERSION ?? "0.15.2";
const defaultPattern =
  "rpc-compat/(client launch|eth_chainId/get-chain-id|eth_blobBaseFee/get-current-blobfee|eth_getBalance/get-balance-unknown-account|eth_getCode/get-code-unknown-account|eth_getStorageAt/get-storage-unknown-account|eth_getTransactionCount/get-nonce-unknown-account|eth_syncing/check-syncing|net_version/get-network-id)";
const testPattern = process.env.ZEVM_HIVE_RPC_COMPAT_PATTERN ?? defaultPattern;
const clientTemplate = join(root, "tools/hive/zevm-client");
const clientDir = join(root, "hive/clients/zevm");
const hiveBin = join(root, "zig-out/hive/hive");
const hiveResultsRoot = join(root, "zig-out/hive/logs");
const hiveOutput = join(root, "zig-out/hive/rpc-compat-smoke.out");

function stripAnsi(value: string): string {
  return value.replace(/\x1B\[[0-?]*[ -/]*[@-~]/g, "");
}

async function run(
  command: string[],
  options: { cwd?: string; capture?: boolean } = {},
): Promise<string> {
  const proc = Bun.spawn(command, {
    cwd: options.cwd,
    stdout: options.capture ? "pipe" : "inherit",
    stderr: options.capture ? "pipe" : "inherit",
  });

  if (!options.capture) {
    const code = await proc.exited;
    if (code !== 0) throw new Error(`${command.join(" ")} exited with ${code}`);
    return "";
  }

  const decoder = new TextDecoder();
  let output = "";
  await Promise.all([
    (async () => {
      for await (const chunk of proc.stdout) {
        const text = decoder.decode(chunk);
        output += text;
        process.stdout.write(text);
      }
    })(),
    (async () => {
      for await (const chunk of proc.stderr) {
        const text = decoder.decode(chunk);
        output += text;
        process.stderr.write(text);
      }
    })(),
  ]);

  const code = await proc.exited;
  if (code !== 0) throw new Error(`${command.join(" ")} exited with ${code}`);
  return output;
}

async function output(command: string[], cwd?: string): Promise<string> {
  const proc = Bun.spawn(command, { cwd, stdout: "pipe", stderr: "pipe" });
  const stdout = await new Response(proc.stdout).text();
  const stderr = await new Response(proc.stderr).text();
  const code = await proc.exited;
  if (code !== 0) throw new Error(`${command.join(" ")} exited with ${code}: ${stderr}`);
  return stdout.trim();
}

async function requireCommand(command: string): Promise<void> {
  await output(["which", command]);
}

function cleanupClientDir(): void {
  if (existsSync(join(clientDir, ".zevm-generated"))) {
    rmSync(clientDir, { recursive: true, force: true });
  }
}

async function main(): Promise<void> {
  await requireCommand("docker");
  await requireCommand("go");

  const executionApisRef =
    process.env.ZEVM_HIVE_EXECUTION_APIS_REF ??
    (await output(["git", "-C", join(root, "execution-apis"), "rev-parse", "HEAD"]));

  for (const sibling of ["voltaire", "guillotine-mini"]) {
    const path = join(root, "..", sibling);
    if (!existsSync(path)) throw new Error(`missing sibling checkout: ${path}`);
  }

  process.on("exit", cleanupClientDir);
  process.on("SIGINT", () => {
    cleanupClientDir();
    process.exit(130);
  });
  process.on("SIGTERM", () => {
    cleanupClientDir();
    process.exit(143);
  });

  if (existsSync(clientDir) && !existsSync(join(clientDir, ".zevm-generated"))) {
    throw new Error(`${clientDir} already exists and was not generated by this script`);
  }
  rmSync(clientDir, { recursive: true, force: true });
  mkdirSync(clientDir, { recursive: true });
  copyFileSync(join(clientTemplate, "Dockerfile"), join(clientDir, "Dockerfile"));
  copyFileSync(join(clientTemplate, "hive.yaml"), join(clientDir, "hive.yaml"));
  writeFileSync(join(clientDir, ".zevm-generated"), "");

  await run([
    "docker",
    "build",
    "--build-context",
    `voltaire=${join(root, "..", "voltaire")}`,
    "--build-context",
    `guillotine-mini=${join(root, "..", "guillotine-mini")}`,
    "--build-arg",
    `ZIG_VERSION=${zigVersion}`,
    "-f",
    join(clientTemplate, "Dockerfile.source"),
    "-t",
    image,
    root,
  ]);

  mkdirSync(dirname(hiveBin), { recursive: true });
  mkdirSync(hiveResultsRoot, { recursive: true });
  await run(["go", "build", "-o", hiveBin, "."], { cwd: join(root, "hive") });

  const hiveLog = await run(
    [
      hiveBin,
      "--sim",
      "ethereum/rpc-compat",
      "--sim.limit",
      testPattern,
      "--sim.buildarg",
      `branch=${executionApisRef}`,
      "--sim.parallelism",
      "1",
      "--client.checktimelimit",
      "45s",
      "--results-root",
      hiveResultsRoot,
      "--client",
      "zevm",
    ],
    { cwd: join(root, "hive"), capture: true },
  );
  writeFileSync(hiveOutput, hiveLog);

  const cleanLog = stripAnsi(hiveLog);
  const summary = cleanLog.match(/simulation ethereum\/rpc-compat finished\s+suites=(\d+)\s+tests=(\d+)\s+failed=(\d+)/);
  if (!summary) throw new Error("Hive rpc-compat smoke did not print a parseable summary");

  const tests = Number(summary[2]);
  const failed = Number(summary[3]);
  if (tests === 0) throw new Error("Hive rpc-compat smoke did not execute any tests");
  if (failed !== 0) throw new Error(`Hive rpc-compat smoke failed ${failed} test(s)`);
}

try {
  await main();
} catch (err) {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
}
